### ISSUE TITLE
Input gets blurred after a character is typed

### ISSUE THREAD

**Issue by megapctr** [hayleigh-dot-dev/gleam-lustre#9]
This happens on `v3.0.0-rc2`, here's a sample snippet that causes the problem.

```
              element.input([
                attribute.on_change(GotUsername),
                attribute.value(dynamic.from(state.username)),
              ]),
```

We explored this a bit more in the [discord thread](https://discord.com/channels/768594524158427167/1114684284423372821)

**Comment by hayleigh-dot-dev** [comment]
Since migrating away from React this is no longer a bug! 🎉
